name-map:
  â›” å¹¿å‘Šæ‹¦æˆª: adblock
  ğŸš€ é€‰æ‹©ä»£ç†: proxy
  ğŸŒ çªç ´é”åŒº: region
  DIRECT: direct

categories:
  redir:
    - "->"
    - ä¸­è½¬
    - OVERALL
  JP:
    - JP
    - Japan
    - æ—¥
    - ğŸ‡¯ğŸ‡µ
  US:
    - US
    - United States
    - ç¾
    - ğŸ‡ºğŸ‡¸
  CZ:
    - CZ
    - Czech Republic
    - æ·å…‹
    - ğŸ‡¨ğŸ‡¿
  HK:
    - HK
    - Hong Kong
    - æ¸¯
    - ğŸ‡­ğŸ‡°
  TW:
    - TW
    - Taiwan
    - å°
    - ğŸ‡¹ğŸ‡¼
  CA:
    - CA
    - Canada
    - åŠ æ‹¿å¤§
    - ğŸ‡¨ğŸ‡¦
  FR:
    - FR
    - French
    - æ³•
    - ğŸ‡«ğŸ‡·
  SG:
    - SG
    - Singapore
    - æ–°åŠ å¡
    - ç‹®åŸ
    - ğŸ‡¸ğŸ‡¬
  GB:
    - GB
    - UK
    - United Kindom
    - Britain
    - è‹±
    - ğŸ‡¬ğŸ‡§
  KR:
    - KR
    - Korea
    - éŸ©
    - ğŸ‡°ğŸ‡·
  PL:
    - PL
    - Poland
    - æ³¢å…°
    - ğŸ‡µğŸ‡±
  DE:
    - DE
    - Germany
    - å¾·
    - ğŸ‡©ğŸ‡ª
  SE:
    - SE
    - Sweden
    - ç‘å…¸
    - ğŸ‡¸ğŸ‡ª
  CH:
    - CH
    - Switzerland
    - ç‘å£«
    - ğŸ‡¨ğŸ‡­
  EE:
    - EE
    - Estonia
    - çˆ±æ²™å°¼äºš
    - ğŸ‡ªğŸ‡ª
  IE:
    - IE
    - Ireland
    - çˆ±å°”å…°
    - ğŸ‡®ğŸ‡ª
  LT:
    - LT
    - Lithuania
    - ç«‹é™¶å®›
    - ğŸ‡±ğŸ‡¹
  NL:
    - NL
    - Netherlands
    - è·å…°
    - ğŸ‡³ğŸ‡±
    
categories_disp:
  JP: ğŸ‡¯ğŸ‡µ æ—¥æœ¬
  US: ğŸ‡ºğŸ‡¸ ç¾å›½
  HK: ğŸ‡­ğŸ‡° é¦™æ¸¯
  TW: ğŸ‡¹ğŸ‡¼ å°æ¹¾
  SG: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
  CA: ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§
  FR: ğŸ‡«ğŸ‡· æ³•å›½
  GB: ğŸ‡¬ğŸ‡§ è‹±å›½
  KR: ğŸ‡°ğŸ‡· éŸ©å›½
  DE: ğŸ‡©ğŸ‡ª å¾·å›½
  CZ: ğŸ‡¨ğŸ‡¿ æ·å…‹
  PL: ğŸ‡µğŸ‡± æ³¢å…°
  SE: ğŸ‡¸ğŸ‡ª ç‘å…¸
  CH: ğŸ‡¨ğŸ‡­ ç‘å£«
  EE: ğŸ‡ªğŸ‡ª çˆ±æ²™å°¼äºš
  IE: ğŸ‡®ğŸ‡ª çˆ±å°”å…°
  LT: ğŸ‡±ğŸ‡¹ ç«‹é™¶å®›
  NL: ğŸ‡³ğŸ‡± è·å…°
  
