name-map:
  â›” å¹¿å‘Šæ‹¦æˆª: adblock
  ğŸš€ é€‰æ‹©ä»£ç†: proxy
  ğŸŒ çªç ´é”åŒº: region
  DIRECT: direct

categories:
  redir:
    - "->"
    - ä¸­è½¬
    - OVERALL
  JP:
    - JP
    - Japan
    - æ—¥
    - ğŸ‡¯ğŸ‡µ
  US:
    - US
    - United States
    - ç¾
    - ğŸ‡ºğŸ‡¸
  CN:
    - CN
    - China
    - ä¸­å›½
    - ä¸Šæµ·
    - æµ™æ±Ÿ
    - å¹¿ä¸œ
    - æ·±åœ³
    - ğŸ‡¨ğŸ‡³
  HK:
    - HK
    - Hong Kong
    - æ¸¯
    - ğŸ‡­ğŸ‡°
  TW:
    - TW
    - Taiwan
    - å°
    - ğŸ‡¹ğŸ‡¼
  CA:
    - CA
    - Canada
    - åŠ æ‹¿å¤§
    - ğŸ‡¨ğŸ‡¦
  FR:
    - FR
    - French
    - æ³•
    - ğŸ‡«ğŸ‡·
  SG:
    - SG
    - Singapore
    - æ–°åŠ å¡
    - ç‹®åŸ
    - ğŸ‡¸ğŸ‡¬
  GB:
    - GB
    - UK
    - United Kindom
    - Britain
    - è‹±
    - ğŸ‡¬ğŸ‡§
  KR:
    - KR
    - Korea
    - éŸ©
    - ğŸ‡°ğŸ‡·
  RU:
    - RU
    - Russia
    - ä¿„
    - ğŸ‡·ğŸ‡º
  DE:
    - DE
    - Germany
    - å¾·
    - ğŸ‡©ğŸ‡ª
  SE:
    - SE
    - Sweden
    - ç‘å…¸
    - ğŸ‡¸ğŸ‡ª
  CH:
    - CH
    - Switzerland
    - ç‘å£«
    - ğŸ‡¨ğŸ‡­
  EE:
    - EE
    - Estonia
    - çˆ±æ²™å°¼äºš
    - ğŸ‡ªğŸ‡ª
  PH
  - PH
  - Philippines
  - è²å¾‹å®¾
categories_disp:
  JP: ğŸ‡¯ğŸ‡µ æ—¥æœ¬
  US: ğŸ‡ºğŸ‡¸ ç¾å›½
  HK: ğŸ‡­ğŸ‡° é¦™æ¸¯
  TW: â” å°æ¹¾
  SG: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
  CA: ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§
  FR: ğŸ‡«ğŸ‡· æ³•å›½
  GB: ğŸ‡¬ğŸ‡§ è‹±å›½
  KR: ğŸ‡°ğŸ‡· éŸ©å›½
  DE: ğŸ‡©ğŸ‡ª å¾·å›½
  CN: ğŸ‡¨ğŸ‡³ ä¸­å›½
  RU: ğŸ‡·ğŸ‡º ä¿„ç½—æ–¯
  SE: ğŸ‡¸ğŸ‡ª ç‘å…¸
  CH: ğŸ‡¨ğŸ‡­ ç‘å£«
  EE: ğŸ‡ªğŸ‡ª çˆ±æ²™å°¼äºš
  PH: PH è²å¾‹å®¾
